### ISSUE TITLE
Modulation order, Rmax, and Scaling factor

### ISSUE THREAD

**Issue by kevinyuan** [zulfadlizainal/5G-NR-Planning-And-Dimensioning#1]
Hi,

Could you clarify if Modulation order and Rmax are considered in the calculation ?

- Q(j)m modulation order (3GPP 38.804, 38.214)
- Rmax, 3GPP 38.214 (Target code Rate R / 1024 )
- f(j) Scaling factor (3GPP 38.306)

**Comment by zulfadlizainal** [comment]
Hi Kevin,

In this [repo](https://github.com/zulfadlizainal/5G-NR-Planning-And-Dimensioning/tree/master/Part%205%20PDSCH/2_DL%20Cell%20Throughput) , codes for DL throughput consider conversion from PDSCH RE to bits using pre-defined spectral efficiency equation. The spectral efficency equation is derived from MCS, Layer, MUMIMO gain and BLER which already considered parameter you mentioned above when it is generated.

But if you are looking for DL throughput calculation which consider direct translation from parameter above, I have specific repository for that in [here](https://github.com/zulfadlizainal/5G-NR-Data-Rates/tree/master/Maximum%20Data%20Rates). In this repo, it translate directly from that specs.
